import { Injectable } from '@angular/core';
import { AngularFirestore, AngularFirestoreCollection, AngularFirestoreDocument} from '@angular/fire/firestore';

@Injectable({
  providedIn: 'root'
})
export class SearchService {

  constructor(private firestore: AngularFirestore) { }
  Hotel:Object = [
    {hotel_name:"Dal Hotels Lagos", City:"Lagos", Country:"Nigeria",Address:"45b Ring Road"},
    {hotel_name:"Dal Hotels Halifax 1", City:"Halifax", Country:"Canada",Address:"777 Brunswick Road"},
    {hotel_name:"Dal Hotels Halifax 2", City:"Halifax", Country:"Canada",Address:"5b Spring Garden"},
    {hotel_name:"Dal Hotels Toronto 1", City:"Toronto", Country:"Canada",Address:"45b Ring Road"},
    {hotel_name:"Dal Hotels Toronto 2", City:"Toronto", Country:"Canada",Address:"45b Ring Road"},
    {hotel_name:"Dal Hotels Toronto 3", City:"Toronto", Country:"Canada",Address:"45b Ring Road"},
    {hotel_name:"Dal Hotels Montreal 1", City:"Montreal", Country:"Canada",Address:"45b Ring Road"},
    {hotel_name:"Dal Hotels Montreal 2", City:"Montreal", Country:"Canada",Address:"45b Ring Road"},
    {hotel_name:"Dal Hotels Montreal 3", City:"Montreal", Country:"Canada",Address:"45b Ring Road"},
    {hotel_name:"Dal Hotels Montreal 4", City:"Montreal", Country:"Canada",Address:"45b Ring Road"},
    {hotel_name:"Dal Hotels Vancover", City:"Vancover", Country:"Canada",Address:"45b Ring Road"}
  ]
  Room:Object = [{beds:1,details:"",cost:1000,size:"small",number:10,hotel_id:"1KVNGyDF5PSbWVLmcRJR",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:1200,size:"medium",number:2,hotel_id:"1KVNGyDF5PSbWVLmcRJR",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.1 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:3000,size:"large",number:3,hotel_id:"5JQf0yuasByfwXx8UZuQ",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.3 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:1000,size:"large",number:8,hotel_id:"7UibjRIPYOjECVB5WGHq",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.5 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:500,size:"medium",number:6,hotel_id:"9sGMUnLUtWtTCgtlkrod",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.2 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:1000,size:"large",number:9,hotel_id:"AYDkmr8wm4kCO1s3GWQP",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.7 km to City Centre"}
  ,{beds:3,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:900,size:"medium",number:23,hotel_id:"BgwvIE1RFRHYRZdgbbFZ",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.8 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:800,size:"small",number:6,hotel_id:"CNono7Ik4K2t0lq2xmXY",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.6 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:700,size:"large",number:4,hotel_id:"CNono7Ik4K2t0lq2xmXY",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.3 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:100,size:"small",number:1,hotel_id:"CNono7Ik4K2t0lq2xmXY",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.2 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:1500,size:"medium",number:10,hotel_id:"DRpb6ckRryHGWhYLHUQW",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.3 km to City Centre"}
  ,{beds:4,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:1200,size:"large",number:11,hotel_id:"JEVCjy2J6CUvlxNQcV2Q",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.9 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:1300,size:"small",number:6,hotel_id:"JEVCjy2J6CUvlxNQcV2Q",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.3 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:2000,size:"medium",number:12,hotel_id:"JFpkpaPzKBvA1rxSvO02",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.2 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:7000,size:"medium",number:13,hotel_id:"JXGhz79p8RS88wmwvTu7",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.6 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:3000,size:"small",number:14,hotel_id:"JXGhz79p8RS88wmwvTu7",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.7 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:5000,size:"small",number:6,hotel_id:"M8Gx3dZfaAuiRnQt7IyJ",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.8 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:9000,size:"large",number:8,hotel_id:"Mf4HDN8yQ40dV5Z7lzq3",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.2 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:2000,size:"medium",number:5,hotel_id:"Pe0vCtBjdtD0M1xPnCSI",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.4 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:4000,size:"small",number:1,hotel_id:"T8vXqGnA4fp431Lg3Gvn",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.9 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:5000,size:"large",number:3,hotel_id:"aR87Qz77VjHCsyIFKwZr",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.2 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:200,size:"medium",number:2,hotel_id:"cW9Ie7p0bcW8eI8IEz8g",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.7 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:400,size:"small",number:6,hotel_id:"eeWfmmL8mAscQPIyfGRo",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.9 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:900,size:"medium",number:8,hotel_id:"p2TqZn6GhEmOCQ04Ap27",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.5 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:700,size:"small",number:7,hotel_id:"qZeDNe2OQyHCt7ryPdBq",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.5 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:2000,size:"large",number:3,hotel_id:"reiqYV9dt53A4eyxJcIh",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.4 km to City Centre"}
  ,{beds:2,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:1000,size:"large",number:9,hotel_id:"zLSXj0HMRA9iupPAAEtb",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.4 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:300,size:"small",number:7,hotel_id:"1KVNGyDF5PSbWVLmcRJR",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.9 km to City Centre"}
  ,{beds:1,details:"The rooms in Dal hotel have been realised completely using original pieces of design and are taken care of down to the last detail.",cost:500,size:"large",number:2,hotel_id:"1KVNGyDF5PSbWVLmcRJR",room_status:"avaliable",img:"../../assets/images/room/",img1:"../../assets/images/room/1.jpg",img2:"../../assets/images/room/2.jpg",img3:"../../assets/images/room/3.jpg",img4:"../../assets/images/room/4.jpg",img5:"../../assets/images/room/5.jpg",img6:"../../assets/images/room/6.jpg",distanceToCityCenter:"0.5 km to City Centre"}
]
  Tag:Object = [{tag_name:"Bar"},{tag_name:"Swimming Pool"},{tag_name:"Tennis Court"},{tag_name:"Football Pitch"},
  {tag_name:"Games"},{tag_name:"Pets"},{tag_name:"Casino"},{tag_name:"Students"}]
  RoomTag:Object = [{room_id:"8UzBr9A13bRLvnf503CA",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"8UzBr9A13bRLvnf503CA",tag_id:"vYWDk0UhMM7QDRcCGPdM"},{room_id:"8UzBr9A13bRLvnf503CA",tag_id:"vYWDk0UhMM7QDRcCGPdM"},{room_id:"CqeDakH5QpCyAtcs46Tu",tag_id:"qz3OB7lyVSCCxkbCW1zx"},{room_id:"CqeDakH5QpCyAtcs46Tu",tag_id:"FIHTwr5KbCrtB6o7ur6i"},{room_id:"CqeDakH5QpCyAtcs46Tu",tag_id:"qz3OB7lyVSCCxkbCW1zx"},{room_id:"CqeDakH5QpCyAtcs46Tu",tag_id:"FIHTwr5KbCrtB6o7ur6i"},{room_id:"CqeDakH5QpCyAtcs46Tu",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"CqeDakH5QpCyAtcs46Tu",tag_id:"FIHTwr5KbCrtB6o7ur6i"},{room_id:"Hb38tET0Ot2QW6XnDgiM",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"Im25WT34qGHDRa74hi8t",tag_id:"qz3OB7lyVSCCxkbCW1zx"},{room_id:"Im25WT34qGHDRa74hi8t",tag_id:"FIHTwr5KbCrtB6o7ur6i"},
  {room_id:"9Rt1egVeXYOiKXeTSRSm",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"9Rt1egVeXYOiKXeTSRSm",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"N4UaaIFsuocEZUfOTW4O",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"QdXutAxqRCwOnslMbnjF",tag_id:"vYWDk0UhMM7QDRcCGPdM"},{room_id:"ROipyeU9I2GU8gaO7wno",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"XmHk0vHRDDkK8mBKDAoP",tag_id:"FIHTwr5KbCrtB6o7ur6i"},{room_id:"Xw6MEgUycVM6Sf306Rzc",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"Xw6MEgUycVM6Sf306Rzc",tag_id:"qz3OB7lyVSCCxkbCW1zx"},{room_id:"Xw6MEgUycVM6Sf306Rzc",tag_id:"GrQ3BmX7R1GVFwZ0UjKN"},{room_id:"Xw6MEgUycVM6Sf306Rzc",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"a5L14hnetzwgu1tOzWLV",tag_id:"qz3OB7lyVSCCxkbCW1zx"},
  {room_id:"a5L14hnetzwgu1tOzWLV",tag_id:"GrQ3BmX7R1GVFwZ0UjKN"},{room_id:"a5L14hnetzwgu1tOzWLV",tag_id:"GrQ3BmX7R1GVFwZ0UjKN"},{room_id:"a5L14hnetzwgu1tOzWLV",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"9uMhCW794oJJmMnkt61k",tag_id:"GrQ3BmX7R1GVFwZ0UjKN"},{room_id:"Im25WT34qGHDRa74hi8t",tag_id:"GrQ3BmX7R1GVFwZ0UjKN"},{room_id:"N4UaaIFsuocEZUfOTW4O",tag_id:"2Crw7Tlm6Pgpx3JyOOdF"},{room_id:"QdXutAxqRCwOnslMbnjF",tag_id:"2Crw7Tlm6Pgpx3JyOOdF"},{room_id:"aPd1tPTufxjO1V7XFCzu",tag_id:"0a2IXlihvsk7wlWFWab7 "},{room_id:"aPd1tPTufxjO1V7XFCzu",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"isdsL9zET50SWl4hl3FJ",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"isdsL9zET50SWl4hl3FJ",tag_id:"qz3OB7lyVSCCxkbCW1zx"},{room_id:"9uMhCW794oJJmMnkt61k",tag_id:"GrQ3BmX7R1GVFwZ0UjKN"},{room_id:"Im25WT34qGHDRa74hi8t",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"ONVhpAGiS1q3ll19UEA",tag_id:"qz3OB7lyVSCCxkbCW1zx"},
  {room_id:"ROipyeU9I2GU8gaO7wno",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"aPd1tPTufxjO1V7XFCzu",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"ccoDfv1Q3ro1gjpcs1Oi",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"ZxSLYL4VWdBuO93qDQ2l",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"ZxSLYL4VWdBuO93qDQ2l",tag_id:"2Crw7Tlm6Pgpx3JyOOdF"},{room_id:"isdsL9zET50SWl4hl3FJ",tag_id:"2Crw7Tlm6Pgpx3JyOOdF"},
  {room_id:"CY983SuXs3qTWbRZ6Kxw ",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"Im25WT34qGHDRa74hi8t",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"ONVhpAGiS1q3ll19UEA",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"ROipyeU9I2GU8gaO7wno",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"aWmd2byxa4AVVhv4SDgN",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"ccoDfv1Q3ro1gjpcs1Oi",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"CY983SuXs3qTWbRZ6Kxw",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"JZJf56TgDjEvoJwuTVo3",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"PMxDFBKGAQp95cAxmfu7",tag_id:"qz3OB7lyVSCCxkbCW1zx"},{room_id:"QdXutAxqRCwOnslMbnjF",tag_id:"GrQ3BmX7R1GVFwZ0UjKN"},{room_id:"aWmd2byxa4AVVhv4SDgN",tag_id:"0a2IXlihvsk7wlWFWab7"},
  {room_id:"dfc6QU6qAhwhIEIVF0Rc",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"XmHk0vHRDDkK8mBKDAoP",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"dfc6QU6qAhwhIEIVF0Rc",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"dfc6QU6qAhwhIEIVF0Rc",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"dfc6QU6qAhwhIEIVF0Rc",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"CY983SuXs3qTWbRZ6Kxw",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"JZJf56TgDjEvoJwuTVo3",tag_id:"0a2IXlihvsk7wlWFWab7"},{room_id:"PMxDFBKGAQp95cAxmfu7",tag_id:"40OmLY0ILvRb5xK2ozmx"},{room_id:"PMxDFBKGAQp95cAxmfu7",tag_id:"qz3OB7lyVSCCxkbCW1zx"},{room_id:"U4SFx0WWNEOM1eSVDZm8",tag_id:"GrQ3BmX7R1GVFwZ0UjKN"},{room_id:"U4SFx0WWNEOM1eSVDZm8",tag_id:"0a2IXlihvsk7wlWFWab7"}]

  setData(){
    
  }

//   setRoomTagData(){
//   for(var tag_roomNo in this.RoomTag){
//     this.firestore.collection("room_tags").add(this.RoomTag[tag_roomNo]);
//   }
// }

// setRoomData(){
//   for(var roomNo in this.Room){
//     this.firestore.collection("rooms").add(this.Room[roomNo]);
//   }
// }

  // setTagData(){
  //   for(var tagNO in this.Tag ){
  //     this.firestore.collection("tags").add(this.Tag[tagNO]);
  //   }
  // }
  // setHotelData(){
  //   for(var hotelNO in this.Hotel ){
  //     this.firestore.collection("hotels").add(this.Hotel[hotelNO]);
  //   }
  // }
}
